/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vista;

import conexion.Conexion;
import controlador.CtrlTransacciones;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

public class InterRegistrarTransaccion extends javax.swing.JInternalFrame {

    public InterRegistrarTransaccion() {
        initComponents();
        this.setSize(new Dimension(426, 268));
        this.setTitle("Registrar Transaccion");
        
        this.cargarCategorias();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxFuente = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDescripcion = new javax.swing.JTextField();
        jTextFieldMonto = new javax.swing.JTextField();
        jButtonRegistrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabelFondo = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setClosable(true);
        setTitle("Registrar Transaccion");
        setPreferredSize(new java.awt.Dimension(432, 260));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tipo de Transaccion: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Ingreso", "Salida" }));
        jPanel1.add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, -1));

        jLabel2.setText("Fuente del Dinero:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 110, 20));

        jComboBoxFuente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Fisico", "Digital" }));
        jPanel1.add(jComboBoxFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 200, -1));

        jLabel3.setText("Ingrese el Monto:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 20));

        jLabel5.setText("Descripcion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, 20));

        jTextFieldDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldDescripcionKeyPressed(evt);
            }
        });
        jPanel1.add(jTextFieldDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 200, -1));
        jPanel1.add(jTextFieldMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 200, -1));

        jButtonRegistrar.setText("Registrar Transaccion");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        jLabel4.setText("Categoria:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 110, 20));

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 200, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 380, 200));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 430, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldDescripcionKeyPressed
        
        if(evt.getKeyCode() == evt.VK_ENTER){
            this.registrarTransaccion();
        }
    }//GEN-LAST:event_jTextFieldDescripcionKeyPressed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        
        this.registrarTransaccion();
        
        jComboBoxCategoria.setSelectedItem("Seleccione...");
        jComboBoxFuente.setSelectedItem("Seleccione...");
        jComboBoxTipo.setSelectedItem("Seleccione...");
        jTextFieldMonto.setText("");
        jTextFieldDescripcion.setText("");
        
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
        
        this.segunCategoria();
        
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxFuente;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDescripcion;
    private javax.swing.JTextField jTextFieldMonto;
    // End of variables declaration//GEN-END:variables

    private void registrarTransaccion(){
        
        String tipo = jComboBoxTipo.getSelectedItem().toString();
        String fuente = jComboBoxFuente.getSelectedItem().toString();
        String montoString = jTextFieldMonto.getText();
        String descripcion = jTextFieldDescripcion.getText();
        String categoria = jComboBoxCategoria.getSelectedItem().toString();
        
        if (montoString.isEmpty() || descripcion.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Complete todos los campos");
            return;
        }
        
        double monto = 0;
        try {
            monto = Double.parseDouble(montoString);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Ingrese un monto valido");
        }
        
        boolean registrado = controlador.CtrlTransacciones.registrarTransaccion(tipo, fuente, monto, descripcion, categoria);
        
        if (registrado) {
            JOptionPane.showMessageDialog(this, "Transaccion registrada con exito");
            jTextFieldDescripcion.setText("");
            jTextFieldDescripcion.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "Error al registrar la transaccion");
        }  
        
        InterGestionarRegistros.actualizarDesdeOtraVentana();
        InterGestionarTransacciones.actualizarDesdeOtraVentana();
    }
    
    private void cargarCategorias(){
        
        Connection con = Conexion.conectar();
        
        String sql = "SELECT nombre FROM categorias ORDER BY nombre";
        try (Statement st = con.createStatement(); ResultSet rs = st.executeQuery(sql)) {
            while (rs.next()) {                
                jComboBoxCategoria.addItem(rs.getString("nombre"));
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error al cargar categorias: " + e);
        }
    }
    
    private void segunCategoria() {
        
        String categoriaSeleccionada = jComboBoxCategoria.getSelectedItem().toString();
        
        if (categoriaSeleccionada.equalsIgnoreCase("Seleccione...")) {
            jComboBoxFuente.setSelectedItem("Seleccione...");
            jComboBoxTipo.setSelectedItem("Seleccione...");
            jTextFieldMonto.setText("");
            jTextFieldDescripcion.setText("");
            
        } else if (categoriaSeleccionada.equalsIgnoreCase("Papá")) {
            jComboBoxFuente.setSelectedItem("Fisico");
            jComboBoxTipo.setSelectedItem("Ingreso");
            jTextFieldMonto.setText("40");
            jTextFieldDescripcion.setText("Dinero Papá");
            
        } else if (categoriaSeleccionada.equalsIgnoreCase("Trabajo")) {
            jComboBoxFuente.setSelectedItem("Fisico");
            jComboBoxTipo.setSelectedItem("Ingreso");
            jTextFieldDescripcion.setText("Uber");
            
        } else if (categoriaSeleccionada.equalsIgnoreCase("Ahorro")){ 
            jComboBoxFuente.setSelectedItem("Fisico");
            jComboBoxTipo.setSelectedItem("Salida");
            jTextFieldMonto.setText("");
            jTextFieldDescripcion.setText("Ahorro Diario");
            
        } else {
            jComboBoxFuente.setSelectedItem("Fisico");
            jComboBoxTipo.setSelectedItem("Salida");
            jTextFieldMonto.setText("");
            jTextFieldDescripcion.setText("");
        }
    }
}
